export enum Types {
  women_s_clothing = 'women_s_clothing',
  men_s_clothing = 'men_s_clothing',
  kid_s_wear = 'kid_s_wear',
  party_wear = 'party_wear',
  jewellery = 'jewellery',
  watches = 'watches',
  shoes = 'shoes',
  handbags = 'handbags',
}

export enum Categories {
  dresses = 'dresses',
  shorts_and_skirts = 'shorts_and_skirts',
  jeans = 'jeans',
  shirts = 'shirts',
  other = 'other',
  slacks = 'slacks',
  frocks = 'frocks',
  skirts = 'skirts',
  long_skirts = 'long_skirts',
  maxi_dress = 'maxi_dress',
  neck_sets = 'neck_sets',
  rings = 'rings',
  chains = 'chains',
  bracelets = 'bracelets',
  leather_strap = 'leather_strap',
  steel_strap = 'steel_strap',
  chain_type = 'chain_type',
  iron_strap = 'iron_strap',
  women_shoes = 'women_shoes',
  men_shoes = 'men_shoes',
  casual_shoes = 'casual_shoes',
  running_shoes = 'running_shoes',
  leather = 'leather',
  cotton_bags = 'cotton_bags',
  wallets = 'wallets',
  jeans_bags = 'jeans_bags',
}
